### ISSUE TITLE
next-bnb build 시 다음과 같은 에러가 발생합니다.

### ISSUE THREAD

**Issue by sjsj0612** [bjpublic/next.js#1]
안녕하세요 ~ 소스코드 다운받아서 실행시켜보았는데요,
next-todo, next-github-list는 잘 실행이 되었습니다.
next-bnb에서 build를 하려고 하니 다음과 같이 에러가 나오는데 어떻게 해결할 수 있을까요?
감사합니다 :) 

-----------------------------------------------------------------------------------------
next-bnb git:(master) ✗ npm run build

> next-bnb@1.0.0 build /Users/1111594/Documents/Projects/next_example/next-bnb
> next build

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
Loaded env from /Users/1111594/Documents/Projects/next_example/next-bnb/.env.local
Failed to compile.

./pages/api/files/upload.ts:24:54
Type error: Property 'path' does not exist on type 'File | File[]'.
  Property 'path' does not exist on type 'File[]'.

  22 |           });
  23 | 
> 24 |           const stream = createReadStream(files.file.path);
     |                                                      ^
  25 | 
  26 |           //* 파일이름
  27 |           const originalFileName = files.file.name.split(".").shift();
info  - Creating an optimized production build .npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! next-bnb@1.0.0 build: `next build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the next-bnb@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by jerrynim** [comment]
안녕하세요~
제가 올린 @types/formidable 의 버전이 1.0.31 일때에는 
files.file의 타입이 formidable.File 타입이였습니다만,
제가 최신 버전의 1.0.32를 설치 하였을때 타입이 File | File[];로 변경된 것을 확인하였습니다.
따라서 여러개의 파일을 받게 될 때 File[] 타입일 경우의 path가 존재하지 않는다는 에러입니다.
사진을 단일로만 업로드할 수 있도록 하였기에 File[]를 고려하지 않아도됩니다.
따라서 최신버전의 타입을 사용하신다면, files.file을 (files.file as formidable.File)로 교체하신다면
빌드가 성공적으로 되시는 것을 확인하실 수 있습니다.

감사힙니다 :)

**Comment by sjsj0612** [comment]
알려주신대로 변경하여 성공했습니다. 감사합니다 👍
