### ISSUE TITLE
리덕스 초기설정 관련해서 질문 드립니다.

### ISSUE THREAD

**Issue by Jwlee134** [bjpublic/next.js#8]
안녕하세요
넥스트비앤비 리덕스 초기설정 코드인데요
```javascript
export type RootState = ReturnType<typeof rootReducer>;

let initialRootState: RootState;

const reducer = (state: any, action: any) => {
  if (action.type === HYDRATE) {
    if (state === initialRootState) {
      return {
        ...state,
        ...action.payload,
      };
    }
    return state;
  }
  return rootReducer(state, action);
};

//* 타입 지원되는 커스텀 useSelector 만들기
export const useSelector: TypedUseSelectorHook<RootState> = useReduxSelector;

const initStore: MakeStore = () => {
  const store = configureStore({
    reducer,
    devTools: true,
  });
  initialRootState = store.getState();
  return store;
};

export const wrapper = createWrapper(initStore);
```
여기서
```javascript
let initialRootState: RootState;

if (state === initialRootState) { ... }

initialRootState = store.getState();
```
위 코드는 혹시 저자님께서 따로 커스텀으로 추가하신 건가요?
with-redux-wrapper 공식 예제랑 투두리스트에서도 저 코드는 찾아볼 수가 없어서요..

결과적으로 저 코드가 있느냐 없느냐에 따라 _NEXT_REDUX_WRAPPER_HYDRATE_ 이 녀석의 행동이 달라지는데요
RegisterRoomFooter.tsx 파일에서
```javascript
useEffect(() => {
    return () => {
      setValidateMode(false);
    };
  }, []);
```
이 코드에 따라서 뒤로 가거나 다음으로 넘어갈 때 validateMode가 false가 되어야 정상인데 공식 예제대로 리덕스 셋팅을 하면
setValidateMode 실행 -> validateMode false -> _NEXT_REDUX_WRAPPER_HYDRATE_ 실행 -> validateMode true
이런 식으로 되어버리네요

저자님이 커스텀으로 추가하신 것으로 추정되는? 코드를 추가하여 리덕스 셋팅을 하면 _NEXT_REDUX_WRAPPER_HYDRATE_ 가 실행되어도 정상적으로 동작하고요

위 현상에 대해서 설명 부탁드리겠습니다..

**Comment by jerrynim** [comment]
안녕하세요~
경험하신대로  componentWillUnmount 를 함수형에서 사용하기위하여 useEffect함수에서 함수를 리턴하여 validateMode 값을 변경하려할 때, NEXT_REDUX_WRAPPER_HYDRATE가 실행되면서 돌아가버리는 이해하기 힘든 현상을 겪으셨을텐데요.
이는 페이지 초기에 클라이언트 측 서버의 리덕스 스토어 값으로 돌아가려는 것으로, 언마운트시에 이것으로 인하여 원하지 않는 결과를 발생시키는 것을 볼 수 있습니다.
이를 해결하기위해 초기 스토어 값을 따로 저장하여 클라이언트에서 해당 기능이 사용되지 않도록 하였습니다.
결과적으로 언마운트가 예상하는데로 발생하게 되고요.

책에 다루기에는 복잡할 수 있다 생각하여, 우선 코드만 적어두었습니다.

감사합니다 :)
